### PR TITLE
Error on master with guidance to retap

### LINKED ISSUE #10: Provide useful error for migrating from `master` -> `main` while upgrading
### Summary
If a user has previously tapped `buildpacks/tap` they will no longer get upgrades via `brew upgrade pack` due to the change of default branch from `master` to `main`.

The steps that should be presented to the user should be:
```bash
brew untap buildpacks/tap
brew tap buildpacks/tap
brew upgrade pack
```

### Proposed solution
https://github.com/Homebrew/brew/issues/7746#issuecomment-649582087

### PR DESCRIPTION
**Pull request by jromero**
Resolves #10

### CODE REVIEW

**Comment by simonjjones** [comment]
This PR appears to request the change to `main`, which would overwrite out generated code. Unless I'm missing something this change should be to our `master` branch?

**Comment by jromero** [comment]
@simonjjones you are right. Updated.

**Comment by simonjjones** [comment]
Looks good to me then, @jromero, is there any good way to validate this _in the wild_ prior to merging?

**Comment by jromero** [comment]
@simonjjones, the wild is your local machine given it's a distributed tap but this is what I ran as the manual test:

```bash

# clean env
brew uninstall pack
brew untap buildpacks/tap

# install via tap (this sets HEAD as `main`)
brew install buildpacks/tap/pack

# simulate previous installation
# manually change HEAD to `master`
cd /usr/local/Homebrew/Library/Taps/buildpacks/homebrew-tap
git fetch origin
git checkout master
git remote set-head origin master

# verify it's already up-to-date
brew upgrade pack

# simulate this change
git merge --ff origin/feature/master-deprecation

# verify notice is received
brew upgrade pack

# follow steps
brew untap buildpacks/tap
brew tap buildpacks/tap
brew upgrade pack # should say it's up-to-date

# verify branch is main
cd /usr/local/Homebrew/Library/Taps/buildpacks/homebrew-tap
git status
```

**Pull request merged**
